using NUnit.Framework;
using UnityEngine;
using UnityEditor;
using System.Linq;
using LighthouseKeepers.Flood;
using LighthouseKeepers.Progression;
namespace LighthouseKeepers.Tests {
public sealed class FoundationTests {
 [Test] public void FloodClampsAndResetPauses(){var go=new GameObject();try{var flood=go.AddComponent<FloodController>();flood.SetHeight(1000);Assert.AreEqual(10.5f,flood.Height);flood.ResumeFlood();flood.ResetFlood();Assert.IsTrue(flood.Paused);Assert.AreEqual(-.25f,flood.Height);}finally{Object.DestroyImmediate(go);}}
 [Test] public void ThresholdFiresOnlyOnCrossingAndSupportsReset(){var go=new GameObject();try{var threshold=go.AddComponent<FloodThreshold>();int count=0;threshold.OnSubmergedChanged.AddListener(_=>count++);threshold.Evaluate(1);threshold.Evaluate(2);Assert.AreEqual(1,count);threshold.Evaluate(-1);Assert.AreEqual(2,count);Assert.IsFalse(threshold.Submerged);}finally{Object.DestroyImmediate(go);}}
 [Test] public void FloodSurgeAcceleratesWithHeight(){var go=new GameObject();try{var flood=go.AddComponent<FloodController>();flood.RiseSpeed=1;flood.SurgePerMetre=0.1f;flood.SetHeight(-0.25f);float low=flood.EffectiveRiseSpeed;Assert.AreEqual(1f,low,0.001f);flood.SetHeight(9.75f);Assert.Greater(flood.EffectiveRiseSpeed,low);Assert.AreEqual(2f,flood.EffectiveRiseSpeed,0.001f);}finally{Object.DestroyImmediate(go);}}
 [Test] public void FloodTimeEstimateIntegratesSurge(){var go=new GameObject();try{var flood=go.AddComponent<FloodController>();flood.ResumeFlood();flood.RiseSpeed=1;flood.SurgePerMetre=0;flood.SetHeight(-0.25f);Assert.AreEqual(5f,flood.TimeToHeight(4.75f),0.001f);flood.SurgePerMetre=0.1f;Assert.AreEqual(Mathf.Log(2f)/0.1f,flood.TimeToHeight(9.75f),0.01f);Assert.AreEqual(0f,flood.TimeToHeight(-1f));flood.Paused=true;Assert.IsTrue(float.IsPositiveInfinity(flood.TimeToHeight(9.75f)));}finally{Object.DestroyImmediate(go);}}
 [Test] public void DangerStagesEscalateAsWaterNearsHead(){var go=new GameObject();try{var flood=go.AddComponent<FloodController>();var monitor=go.AddComponent<FloodDangerMonitor>();typeof(FloodDangerMonitor).GetMethod("OnEnable",System.Reflection.BindingFlags.Instance|System.Reflection.BindingFlags.NonPublic).Invoke(monitor,null);flood.ResumeFlood();flood.SetHeight(0f);int transitions=0;monitor.StageChanged+=(_,__)=>transitions++;monitor.EvaluateHead(3f);Assert.AreEqual(FloodDangerStage.Safe,monitor.Stage);monitor.EvaluateHead(1.5f);Assert.AreEqual(FloodDangerStage.Watch,monitor.Stage);monitor.EvaluateHead(0.8f);Assert.AreEqual(FloodDangerStage.Warning,monitor.Stage);monitor.EvaluateHead(0.3f);Assert.AreEqual(FloodDangerStage.Critical,monitor.Stage);monitor.EvaluateHead(-0.1f);Assert.AreEqual(FloodDangerStage.Submerged,monitor.Stage);Assert.AreEqual(5,transitions);monitor.EvaluateHead(-0.1f);Assert.AreEqual(5,transitions);}finally{Object.DestroyImmediate(go);}}
 [Test] public void SurfaceToneTracksNormalizedHeight(){var go=new GameObject();try{var surface=go.AddComponent<FloodSurface>();Assert.AreEqual(0f,surface.ToneFor(-0.25f),0.001f);Assert.AreEqual(1f,surface.ToneFor(10.5f),0.001f);Assert.AreEqual(0.5f,surface.ToneFor(5.125f),0.01f);}finally{Object.DestroyImmediate(go);}}
 [Test] public void DaysBecomeMeasurablyMoreIntense(){var days=AssetDatabase.FindAssets("t:DayProfile").Select(g=>AssetDatabase.LoadAssetAtPath<DayProfile>(AssetDatabase.GUIDToAssetPath(g))).OrderBy(d=>d.Day).ToArray();Assert.AreEqual(5,days.Length);for(int i=1;i<5;i++){Assert.Greater(days[i].StormIntensity,days[i-1].StormIntensity);Assert.Greater(days[i].FloodRiseRate,days[i-1].FloodRiseRate);Assert.Less(days[i].LightningInterval,days[i-1].LightningInterval);Assert.Greater(days[i].LeakCount,days[i-1].LeakCount);}}
 [Test] public void BuildIncludesBootstrapFirstAndAllEightScenes(){var scenes=EditorBuildSettings.scenes.Where(s=>s.enabled).ToArray();Assert.AreEqual(8,scenes.Length);StringAssert.EndsWith("LK_Bootstrap.unity",scenes[0].path);Assert.AreEqual(8,scenes.Select(s=>s.path).Distinct().Count());}
}}
